### ISSUE TITLE
Act 4 Modelo de Neg

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipo-exe#1]
@
[Act 4 Modelo de Neg.pdf](https://github.com/user-attachments/files/17248104/Act.4.Modelo.de.Neg.pdf)

**Comment by josealfredo79** [comment]
Calificacion..????

**Comment by PedroGarcia15** [comment]
Base a la rubrica, la calificación es de 18 de 20

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by Ariadnamonserrat10** [comment]
19 de 20 por que les falto unas partes

**Comment by josealfredo79** [comment]
Revisado...
